# SwiftLint configuration for Auto-Focus
# See https://realm.github.io/SwiftLint/configuration/ for all options

# Enable recommended rules
opt_in_rules:
  - empty_count
  - explicit_init
  - fatal_error_message
  - force_unwrapping
  - implicitly_unwrapped_optional
  - missing_docs
  - private_outlet
  - redundant_nil_coalescing
  - sorted_imports
  - switch_case_on_newline
  - trailing_closure
  - unused_declaration

# Exclude generated, build, and deprecated code
excluded:
  - builds
  - deprecated
  - auto-focus.xcodeproj
  - auto-focusUITests

# Customize some rules
line_length:
  warning: 120
  error: 160
identifier_name:
  min_length: 2
  excluded:
    - i
    - x
    - y
    - id
    - db
    - ui

# Allow TODOs but warn
todo:
  severity: warning

# Allow force casts in tests
force_cast:
  severity: warning
  excluded:
    - auto-focusTests

# Allow print in debug
print:
  severity: warning

# Required header for all files
required_headers:
  - "//  Auto-Focus"

# Enable all default rules
